### ISSUE TITLE
Bug report - Entries for comments no longer appears since 30 March 2021 and some buggy entries

### ISSUE THREAD

**Issue by Miss-Toki** [KockaAdmiralac/KockaLogger#49]
## Description
Since 30 March 2021, entries from posting/editing/reporting/deleting comments do no longer appear for unknown reason. And for now the bug is still ongoing. Would it be fixed the problem if the issue is from Logger ? Thank you.

## Expected behavior
Entries should appear like `<username> (t|c) posted a comment (<size>) on <PAGENAME>` for example https://discord.com/channels/244398471044399106/244399776315998208/826410811751792660 (WW)
`TokihikoH11 (t|c) protected User:TokihikoH11/RCLogger test ‎edit=autoconfirmed (expires 21:22, 15 November 2021 (UTC)) to  (Testing)` but  `User:TokihikoH11/RCLogger test ‎edit=autoconfirmed (expires 21:22, 15 November 2021 (UTC))` appears to be blue like a link but only `User:TokihikoH11/RCLogger test` should appear in blue (see https://discord.com/channels/499291143201095700/501465557569372160/909916112207085568 - Vocaloid Wiki server)

**Comment by KockaAdmiralac** [comment]
The reason is that comments no longer contain the full URL (including the title) for the page they were posted on, because these messages would overflow into a second IRC message (IRC messages are limited to 255 bytes, iirc). The overflow wasn't a problem for KockaLogger, but it was a problem for Wiki-Bot (which, iirc, queries the API anyways), so @Markus-Rost requested the change to the message format shortly after comment support was added and the URL was changed to only contain `curid` (which KockaLogger would have to query the API for, and support for that was *just* removed when comment support was added).

Since none of my wikis actively use comments, this wasn't a priority for me. I can look into temporarily making them relay without a page title (but not very soon, at least in a few weeks) and then try readding the API queries with Redis caching later.

As for protection, I think they somehow changed protection logs when they switched to UCP and now they might have changed them back (or changed them in a different way) so I'll probably look into that along with the temporary fix for comments.
